/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;
import com.fazecast.jSerialComm.SerialPort;
import java.util.Scanner;

/**
 *
 * @author Muchwat
 */
public final class SystemControl extends javax.swing.JFrame {
   
    /**
     * Creates new form SystemControl
     */
    //SettingsConfig set = new SettingsConfig();  
    //SerialPort selectedPort = SerialPort.getCommPort(set.getConnection("USBPORT"));
    
    public SystemControl() {
        initComponents();
        controlState();
        //connection();
       
    }
    
    
    //public void connection(){
   /*  if (selectedPort == null) {
            return;

        } else if (selectedPort.openPort()) {
            System.out.println(selectedPort.getSystemPortName() + " successfully opened.");
           

        } else {
            System.out.println(selectedPort.getSystemPortName() + " failed to open.");
            return;
        }
      
       selectedPort.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING,0,0);
      
        Scanner data = new Scanner(selectedPort.getInputStream());
        while(data.hasNextLine()){
                  int readins = Integer.parseInt(data.nextLine());
                System.out.println(readins);
                 
              }*/
             
    //}
     
    public void controlState(){
     String sys = "System";
     String sysstate = "";//set.getSettings(sys);
     if(sysstate.contains("on")){         
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       sysOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       sysOn.setIcon(sr);
     
     }else{
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       sysOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       sysOn.setIcon(sr); 
     }
     
     String alm = "Alarm";
     String almstate = "";//set.getSettings(alm);
     if(almstate.contains("on")){         
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       almOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       almOn.setIcon(sr);
     
     }else{
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       almOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       almOn.setIcon(sr); 
     }
     
     String fn = "Fun";
     String fnstate = "";//set.getSettings(fn);
     if(fnstate.contains("on")){         
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       fnOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       fnOn.setIcon(sr);
     
     }else{
       ImageIcon s = new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       fnOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       fnOn.setIcon(sr); 
     }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        system = new javax.swing.JLabel();
        sysOff = new javax.swing.JLabel();
        sysOn = new javax.swing.JLabel();
        almOn = new javax.swing.JLabel();
        almOff = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnOn = new javax.swing.JLabel();
        fnOff = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Container = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 615));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/menubtn.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        tittle.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("System Control");
        getContentPane().add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 1000, 25));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 5, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/cancel.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 5, -1, -1));

        system.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        system.setForeground(new java.awt.Color(255, 255, 255));
        system.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        system.setText("System");
        getContentPane().add(system, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 240, 70, -1));

        sysOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/offdis.png"))); // NOI18N
        sysOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sysOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sysOffMouseClicked(evt);
            }
        });
        getContentPane().add(sysOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        sysOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/on.png"))); // NOI18N
        sysOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sysOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sysOnMouseClicked(evt);
            }
        });
        getContentPane().add(sysOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 240, -1, -1));

        almOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        almOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/on.png"))); // NOI18N
        almOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        almOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almOnMouseClicked(evt);
            }
        });
        getContentPane().add(almOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 280, -1, -1));

        almOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        almOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/offdis.png"))); // NOI18N
        almOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        almOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almOffMouseClicked(evt);
            }
        });
        getContentPane().add(almOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Alarm");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 280, 70, -1));

        fnOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fnOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/on.png"))); // NOI18N
        fnOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fnOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnOnMouseClicked(evt);
            }
        });
        getContentPane().add(fnOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 320, -1, -1));

        fnOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/offdis.png"))); // NOI18N
        fnOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnOffMouseClicked(evt);
            }
        });
        getContentPane().add(fnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Fan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 320, 70, 20));

        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/active.png"))); // NOI18N
        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
      ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/cancelf.png"));
      exit.setIcon(a);
      
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
      ImageIcon ab = new ImageIcon(getClass().getResource("/AppPackage/cancel.png"));
      exit.setIcon(ab);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
       ImageIcon af = new ImageIcon(getClass().getResource("/AppPackage/minf.png"));
       min.setIcon(af);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
       ImageIcon ag = new ImageIcon(getClass().getResource("/AppPackage/min.png"));
       min.setIcon(ag);
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(SystemControl.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
       ImageIcon gf = new ImageIcon(getClass().getResource("/AppPackage/menu-btn.png"));
       menu.setIcon(gf);
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
       ImageIcon gh = new ImageIcon(getClass().getResource("/AppPackage/menubtn.png"));
       menu.setIcon(gh);
    }//GEN-LAST:event_menuMouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
       Mainclass s = new Mainclass();
       s.setVisible(true);
       //selectedPort.closePort();
       this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void sysOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sysOffMouseClicked
       String tittle = "System";
       String state = "off";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       sysOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       sysOn.setIcon(sr); 
      // set.saveSettings(tittle, state);
    }//GEN-LAST:event_sysOffMouseClicked

    private void sysOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sysOnMouseClicked
       String tittle = "System";
       String state = "on";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       sysOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       sysOn.setIcon(sr);
       //set.saveSettings(tittle, state);
    }//GEN-LAST:event_sysOnMouseClicked

    private void almOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almOffMouseClicked
       String tittle = "Alarm";
       String state = "off";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       almOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       almOn.setIcon(sr);
       //set.saveSettings(tittle, state);
    }//GEN-LAST:event_almOffMouseClicked

    private void almOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almOnMouseClicked
       String tittle = "Alarm";
       String state = "on";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       almOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       almOn.setIcon(sr);
      // set.saveSettings(tittle, state);
    }//GEN-LAST:event_almOnMouseClicked

    private void fnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnOffMouseClicked
       String tittle = "Fun";
       String state = "off";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/off.png"));
       fnOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/ondis.png"));
       fnOn.setIcon(sr);
       //set.saveSettings(tittle, state);
    }//GEN-LAST:event_fnOffMouseClicked

    private void fnOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnOnMouseClicked
       String tittle = "Fun";
       String state = "on";
       ImageIcon s= new ImageIcon(getClass().getResource("/AppPackage/offdis.png"));
       fnOff.setIcon(s);
       ImageIcon sr = new ImageIcon(getClass().getResource("/AppPackage/on.png"));
       fnOn.setIcon(sr);
       //set.saveSettings(tittle, state);
    }//GEN-LAST:event_fnOnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemControl().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Container;
    private javax.swing.JLabel almOff;
    private javax.swing.JLabel almOn;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fnOff;
    private javax.swing.JLabel fnOn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel min;
    private javax.swing.JLabel sysOff;
    private javax.swing.JLabel sysOn;
    private javax.swing.JLabel system;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
