/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;

/**
 *
 * @author Muchwat
 */
public class Temphumidity extends javax.swing.JFrame {

    /**
     * Creates new form Temphumidity
     */
    public Temphumidity() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        tempbtn = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        humidbtn = new javax.swing.JLabel();
        humid = new javax.swing.JLabel();
        Container = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/menubtn.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Temperature and Humidity thermometers");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 1000, 20));

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 5, -1, -1));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/cancel.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 5, -1, -1));

        tempbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/therrmbtn.png"))); // NOI18N
        tempbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tempbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tempbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tempbtnMouseExited(evt);
            }
        });
        getContentPane().add(tempbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 390, -1, -1));

        temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/temp-Recovered.png"))); // NOI18N
        getContentPane().add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 155, -1, -1));

        humidbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        humidbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/therrmbtn.png"))); // NOI18N
        humidbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        humidbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                humidbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                humidbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                humidbtnMouseExited(evt);
            }
        });
        getContentPane().add(humidbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 390, -1, -1));

        humid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        humid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/humidity-Recovered.png"))); // NOI18N
        getContentPane().add(humid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 155, -1, -1));

        Container.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/active.png"))); // NOI18N
        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
       ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/cancelf.png"));
       exit.setIcon(a);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
       ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/cancel.png"));
       exit.setIcon(a);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
       ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/minf.png"));
       min.setIcon(a);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/min.png"));
        min.setIcon(a);
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(Temphumidity.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
       ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/menu-btn.png"));
       menu.setIcon(a);
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/menubtn.png"));
        menu.setIcon(a);
    }//GEN-LAST:event_menuMouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
       new Mainclass().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void tempbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempbtnMouseEntered
        ImageIcon ac = new ImageIcon(getClass().getResource("/AppPackage/therrmbtnf.png"));
        tempbtn.setIcon(ac);
    }//GEN-LAST:event_tempbtnMouseEntered

    private void tempbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempbtnMouseExited
       ImageIcon ac = new ImageIcon(getClass().getResource("/AppPackage/therrmbtn.png"));
       tempbtn.setIcon(ac);
    }//GEN-LAST:event_tempbtnMouseExited

    private void tempbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempbtnMouseClicked
        Temperature temperature = new Temperature();
        
    }//GEN-LAST:event_tempbtnMouseClicked

    private void humidbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humidbtnMouseEntered
       ImageIcon ac = new ImageIcon(getClass().getResource("/AppPackage/therrmbtnf.png"));
       humidbtn.setIcon(ac);
    }//GEN-LAST:event_humidbtnMouseEntered

    private void humidbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humidbtnMouseExited
       ImageIcon ac = new ImageIcon(getClass().getResource("/AppPackage/therrmbtn.png"));
       humidbtn.setIcon(ac);
    }//GEN-LAST:event_humidbtnMouseExited

    private void humidbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humidbtnMouseClicked
       humidity hmdty = new humidity();
    }//GEN-LAST:event_humidbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temphumidity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temphumidity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temphumidity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temphumidity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temphumidity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Container;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel humid;
    private javax.swing.JLabel humidbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel min;
    private javax.swing.JLabel temp;
    private javax.swing.JLabel tempbtn;
    // End of variables declaration//GEN-END:variables
}
