/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import javax.swing.ImageIcon;

/**
 *
 * @author Muchwat
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public User() throws SQLException {
        initComponents();
        conn = DriverManager.getConnection("jdbc:sqlite:userdata.db");
        Update_table();
    }
    
    private void Update_table(){
  //timer.start();

    try{
    String sql ="select * from users";
   pst=conn.prepareStatement(sql);
   rs=pst.executeQuery();
   userData.setModel(DbUtils.resultSetToTableModel(rs));
 
 
    }
    catch(Exception e){
    //JOptionPane.showMessageDialog(null, e);
 
     }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userData = new javax.swing.JTable();
        pass2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pass1 = new javax.swing.JLabel();
        dataid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Container = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 5, -1, -1));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/cancel.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 5, -1, -1));

        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/menubtn.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        userData.setBackground(new java.awt.Color(0, 102, 204));
        userData.setForeground(new java.awt.Color(204, 204, 204));
        userData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userData.setAlignmentX(1.0F);
        userData.setAlignmentY(1.0F);
        userData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userData.setEditingRow(2);
        userData.setFocusable(false);
        userData.setGridColor(new java.awt.Color(0, 51, 255));
        userData.setName(""); // NOI18N
        userData.setOpaque(false);
        userData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDataMouseClicked(evt);
            }
        });
        userData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userDataKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(userData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 620, 430));

        pass2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        pass2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 306, 160, 20));

        name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 218, 160, 20));

        pass1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 262, 160, 20));

        dataid.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        dataid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dataid, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 174, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 444, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 406, -1, -1));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/userbtn.PNG"))); // NOI18N
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 440, 170, -1));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/userbtn.PNG"))); // NOI18N
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 400, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/userdata.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 90, 198, 430));

        Container.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/active.png"))); // NOI18N
        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
       ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/cancelf.png"));
       exit.setIcon(f);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
       ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/cancel.png"));
       exit.setIcon(f);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
       ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/minf.png"));
       min.setIcon(f);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/min.png"));
        min.setIcon(f);
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(User.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
       ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/menu-btn.png"));
       menu.setIcon(f);
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
       ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/menubtn.png"));
       menu.setIcon(f);
    }//GEN-LAST:event_menuMouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
       
           try {
               if(!conn.isClosed() || conn!=null){
                   conn.close();
               }      } catch (SQLException ex) {
               Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
           }finally{
            Mainclass s = new Mainclass();
            s.setVisible(true);
            this.dispose();}
    }//GEN-LAST:event_menuMouseClicked

    private void userDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDataMouseClicked
        
        try{
         int row = userData.getSelectedRow();
         String id =(userData.getModel().getValueAt(row, 0).toString());
         String sql ="select * from users where id='"+id+"' ";
         pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          if(rs.next()){
          
          String userid =rs.getString("id");
          dataid.setText(userid);
          String uname =rs.getString("name");
          name.setText(uname);
          String passw1 =rs.getString("password");
          pass1.setText(passw1);
          String paas2 =rs.getString("password");
          pass2.setText(paas2);
          }
        
        }catch(Exception e){
        
        //JOptionPane.showMessageDialog(null, e);
        }/*finally {
           if (conn != null) {
               try {
                    conn.close(); // <-- This is important
           } catch (SQLException e) {
           
         }
        }} */  
    }//GEN-LAST:event_userDataMouseClicked

    private void userDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userDataKeyReleased
         if (evt.getKeyCode()== KeyEvent.VK_DOWN || evt.getKeyCode()== KeyEvent.VK_UP){
             try{
                 int row = userData.getSelectedRow();
                 String id =(userData.getModel().getValueAt(row, 0).toString());
                 String sql ="select * from users where id='"+id+"' ";
                 pst=conn.prepareStatement(sql);
                 rs=pst.executeQuery();
                 if(rs.next()){
                     
                     String userid =rs.getString("id");
                     dataid.setText(userid);
                     String uname =rs.getString("name");
                     name.setText(uname);
                     String passw1 =rs.getString("password");
                     pass1.setText(passw1);
                     String paas2 =rs.getString("password");
                     pass2.setText(paas2);
                 }
                 
                 
             }        catch(SQLException e)
             {
                 // if the error message is "out of memory",
                 // it probably means no database file is found
                 System.err.println(e.getMessage());
             }/*finally {
           if (conn != null) {
               try {
                    conn.close(); // <-- This is important
           } catch (SQLException e) {
           
         }
        }} */  
         } else {
         }
    }//GEN-LAST:event_userDataKeyReleased

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        
        String sql = "delete from users where id =?";
        try
        {
           // create a database connection
          pst =conn.prepareStatement(sql);
          pst.setString(1, dataid.getText());
          pst.execute();
          Update_table();
          dataid.setText("User data below is deleted");
        }
        catch(SQLException e)
        {
          // if the error message is "out of memory", 
          // it probably means no database file is found
          System.err.println(e.getMessage());
        }/*finally {
           if (conn != null) {
               try {
                    conn.close(); // <-- This is important
           } catch (SQLException e) {
           
         }
        }} */  
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new User().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Container;
    private javax.swing.JLabel dataid;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel min;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pass1;
    private javax.swing.JLabel pass2;
    private javax.swing.JTable userData;
    // End of variables declaration//GEN-END:variables
}
